spring.application.name=ajax_app_java
spring.sql.init.mode=always
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ajax_app_java
spring.datasource.username=f_ozaki
spring.datasource.password=8G2rTi1
mybatis.configuration.map-underscore-to-camel-case=true